namespace PTL.Contracts.Scheme;

// Public API contract for GET /api/schemes/{schemeId}; field set matches PtaBusinessObjects
// BusinessObjects.Schemes.Scheme as fetched by spgSchemeBySchemeId (Scheme Core scope only -
// Tests/SchemeCurrency/Viewers/Tabulations and the participant-scheme CanEdit* flags are excluded,
// see docs/analysis/scheme-analysis.md and docs/migration/scheme-migration.md).
public sealed record SchemeResponse(
    Guid SchemeId,
    Guid SharedId,
    int YearId,
    string Identifier,
    string Name,
    Guid ScheduleId,
    Guid ScheduleCodeId,
    DateTime? StartDate,
    bool DistributionMonthApr,
    bool DistributionMonthMay,
    bool DistributionMonthJun,
    bool DistributionMonthJul,
    bool DistributionMonthAug,
    bool DistributionMonthSep,
    bool DistributionAsAvailable,
    bool DistributionMonthOct,
    bool DistributionMonthNov,
    bool DistributionMonthDec,
    bool DistributionMonthJan,
    bool DistributionMonthFeb,
    bool DistributionMonthMar,
    int WeekNumber,
    Guid DayOfWeekId,
    int NumberOfSamples,
    int? SampleNoSequence,
    string SampleOrigin,
    int Deadline,
    string Subcontractor,
    bool CombinedPackaging,
    Guid? Postage,
    string? CustomsVolume,
    string SamplePackingInstructions,
    bool RequiresAssessment,
    bool CommentsRequired,
    bool Pilot,
    bool LimitedSampleAvailability,
    bool Accredited,
    bool NoVLALabs,
    bool ComerciallyAvailable,
    string? CustomsDescription,
    bool DataConsentDeclarationActive,
    string? DataConsentDeclarationText,
    string Instructions,
    bool DateOfReceipt,
    bool StorageConditions,
    bool ConditionOnReceipt,
    Guid? TestConsultant1,
    Guid? TestConsultant2,
    Guid? TestConsultant3,
    Guid? TestConsultantTabulationId,
    bool UseExternalReference,
    bool StoreRatings,
    Guid? Assessor1,
    Guid? Assessor2,
    Guid? Assessor3,
    Guid? Assessor4,
    string? StandardTabulationText,
    DateTime LastModified,
    bool IsReadOnly);
