namespace PTL.Contracts.Scheme;

// Same editable field set as CreateSchemeRequest. SchemeId comes from the route; SharedId and
// LastModified are preserved/stamped server-side. RequiresAssessment is accepted here (spuScheme
// always requires a value) but SchemeService overwrites it with the existing persisted value -
// mirrors the legacy Scheme.aspx.vb behaviour of disabling the checkbox once a SchemeId exists.
public sealed record UpdateSchemeRequest(
    int YearId,
    string Identifier,
    string Name,
    Guid ScheduleId,
    Guid ScheduleCodeId,
    DateTime? StartDate,
    bool DistributionMonthApr,
    bool DistributionMonthMay,
    bool DistributionMonthJun,
    bool DistributionMonthJul,
    bool DistributionMonthAug,
    bool DistributionMonthSep,
    bool DistributionAsAvailable,
    bool DistributionMonthOct,
    bool DistributionMonthNov,
    bool DistributionMonthDec,
    bool DistributionMonthJan,
    bool DistributionMonthFeb,
    bool DistributionMonthMar,
    int WeekNumber,
    Guid DayOfWeekId,
    int NumberOfSamples,
    string SampleOrigin,
    int Deadline,
    string Subcontractor,
    bool CombinedPackaging,
    Guid? Postage,
    string? CustomsVolume,
    string SamplePackingInstructions,
    bool RequiresAssessment,
    bool CommentsRequired,
    bool Pilot,
    bool LimitedSampleAvailability,
    bool Accredited,
    bool NoVLALabs,
    bool ComerciallyAvailable,
    string? CustomsDescription,
    bool DataConsentDeclarationActive,
    string? DataConsentDeclarationText,
    string Instructions,
    bool DateOfReceipt,
    bool StorageConditions,
    bool ConditionOnReceipt,
    Guid? TestConsultant1,
    Guid? TestConsultant2,
    Guid? TestConsultant3,
    Guid? TestConsultantTabulationId,
    bool UseExternalReference,
    bool StoreRatings,
    Guid? Assessor1,
    Guid? Assessor2,
    Guid? Assessor3,
    Guid? Assessor4,
    string? StandardTabulationText);
