namespace PTL.Contracts.Participant;

// Public API contract for GET /api/participant-schemes/{participantSchemeId} - matches legacy
// PtaBusinessObjects.BusinessObjects.Contracts.ParticipantScheme as fetched by
// spgParticipantSchemeByParticipantSchemeId (see docs/analysis/participant-analysis.md).
public sealed record ParticipantSchemeResponse(
    Guid ParticipantSchemeId,
    Guid ContractId,
    Guid ParticipantId,
    Guid SchemeId,
    bool DistributionMonthJan,
    bool DistributionMonthFeb,
    bool DistributionMonthMar,
    bool DistributionMonthApr,
    bool DistributionMonthMay,
    bool DistributionMonthJun,
    bool DistributionMonthJul,
    bool DistributionMonthAug,
    bool DistributionMonthSep,
    bool DistributionMonthOct,
    bool DistributionMonthNov,
    bool DistributionMonthDec,
    bool CanEditJan,
    bool CanEditFeb,
    bool CanEditMar,
    bool CanEditApr,
    bool CanEditMay,
    bool CanEditJun,
    bool CanEditJul,
    bool CanEditAug,
    bool CanEditSep,
    bool CanEditOct,
    bool CanEditNov,
    bool CanEditDec,
    int NumberOfSetsRequired,
    string? ExternalReference,
    string? Contact,
    bool IsRemoved,
    bool ImportExportLicenceRequired,
    bool CustomsCertificateRequired,
    bool NonFeePaying,
    string? PackingInstructions,
    bool IsWeightedPricing,
    bool DataConsentDeclarationGiven,
    bool IsOverrideJan,
    bool IsOverrideFeb,
    bool IsOverrideMar,
    bool IsOverrideApr,
    bool IsOverrideMay,
    bool IsOverrideJun,
    bool IsOverrideJul,
    bool IsOverrideAug,
    bool IsOverrideSep,
    bool IsOverrideOct,
    bool IsOverrideNov,
    bool IsOverrideDec,
    decimal Price,
    string ParticipantDisplayName,
    string SchemeDisplayName,
    Guid? GroupAddressId = null);
