using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PTL.InternalWeb.Features.Participant;

public sealed record ParticipantListViewModel(
    Guid CustomerId,
    string? SearchTerm,
    bool IncludeInactive,
    int Page,
    int PageSize,
    int TotalCount,
    IReadOnlyList<PTL.Contracts.Participant.ParticipantSummaryResponse> Participants);

public sealed class ParticipantFormViewModel
{
    public Guid ParticipantId { get; set; }
    public Guid CustomerId { get; set; }
    public Guid SsoId { get; set; }

    [Required(ErrorMessage = "Enter a lab code.")]
    public string LabCode { get; set; } = string.Empty;

    [Required(ErrorMessage = "Enter a lab name.")]
    public string LabName { get; set; } = string.Empty;

    public Guid LabTypeId { get; set; }

    // Populated by ParticipantController before the view is rendered - see /api/lookups/lab-types.
    public IEnumerable<SelectListItem> LabTypeOptions { get; set; } = [];

    [Required(ErrorMessage = "Enter a contact name.")]
    public string ContactName { get; set; } = string.Empty;

    public string Organisation { get; set; } = string.Empty;
    public string Address1 { get; set; } = string.Empty;
    public string Address2 { get; set; } = string.Empty;
    public string Address3 { get; set; } = string.Empty;
    public string Address4 { get; set; } = string.Empty;
    public string Address5 { get; set; } = string.Empty;
    public Guid CountryId { get; set; }

    // Populated by ParticipantController before the view is rendered - see /api/lookups/countries.
    public IEnumerable<SelectListItem> CountryOptions { get; set; } = [];

    public string Telephone { get; set; } = string.Empty;
    public string Fax { get; set; } = string.Empty;
    [EmailAddress(ErrorMessage = "Enter a valid email address.")]
    public string Email { get; set; } = string.Empty;
    [EmailAddress(ErrorMessage = "Enter a valid alternative email address.")]
    public string Email2 { get; set; } = string.Empty;
    public string Comments { get; set; } = string.Empty;
    public bool IsActive { get; set; } = true;

    // Display-only - server-generated by ParticipantService (set on deactivate, cleared on
    // reactivate/create), never posted back or trusted from the client. Only rendered on the Edit
    // form, and only when a value is present - never shown on Create, since the date is only ever
    // generated after the participant is first saved.
    public DateTime? InactiveDate { get; set; }

    // Populated by ParticipantController from the parent Customer (ICustomerApiClient) so
    // _ParticipantForm.cshtml's "Copy from customer contact" button - mirroring legacy
    // Participant.aspx.vb ButtonCopyDetails_Click - can copy client-side with no extra round trip.
    public string CustomerContactName { get; set; } = string.Empty;
    public string CustomerOrganisation { get; set; } = string.Empty;
    public string CustomerAddress1 { get; set; } = string.Empty;
    public string CustomerAddress2 { get; set; } = string.Empty;
    public string CustomerAddress3 { get; set; } = string.Empty;
    public string CustomerAddress4 { get; set; } = string.Empty;
    public string CustomerAddress5 { get; set; } = string.Empty;
    public Guid CustomerCountryId { get; set; }
    public string CustomerTelephone { get; set; } = string.Empty;
    public string CustomerFax { get; set; } = string.Empty;
    public string CustomerEmail { get; set; } = string.Empty;
}
