namespace PTL.Contracts.Customer;

// Field set mirrors CustomerResponse minus server-generated values (CustomerId, QalNumber,
// InitialStartDate). IsActive defaults to true, matching Customer.DataPortal_Create() in the
// legacy app, which always creates a new customer as active unless the form explicitly unchecks it.
public sealed record CreateCustomerRequest(
    string RegisteredFileNumber,
    string Name,
    string PreviousName,
    Guid CustomerTypeId,
    string VatNumber,
    Guid VatRatingId,
    string AccountNumber,
    string CustomerFinanceId,
    string ContactName,
    string Organisation,
    string Address1,
    string Address2,
    string Address3,
    string Address4,
    string Address5,
    Guid CountryId,
    string Telephone,
    string Telephone2,
    string Fax,
    string Email,
    Guid CurrencyId,
    string Comments,
    string PostageArrangements,
    bool PaymentNonUK,
    string InvoiceName,
    string InvoiceOrganisation,
    string InvoiceAddress1,
    string InvoiceAddress2,
    string InvoiceAddress3,
    string InvoiceAddress4,
    string InvoiceAddress5,
    Guid InvoiceCountryId,
    string InvoiceTelephone,
    string InvoiceTelephone2,
    string InvoiceFax,
    string InvoiceEmail,
    bool IsActive = true,
    bool CanOrderOnline = false,
    Guid? CustomerStatusId = null);
