namespace PTL.Contracts.Customer;

// Public API contract for GET /api/customers/{customerId}; field set matches the legacy
// Customer.asmx GetCustomer() response and PtaBusinessObjects Customer business object.
public sealed record CustomerResponse(
    Guid CustomerId,
    string QalNumber,
    string RegisteredFileNumber,
    string Name,
    string PreviousName,
    Guid CustomerTypeId,
    string VatNumber,
    Guid VatRatingId,
    string AccountNumber,
    string CustomerFinanceId,
    string ContactName,
    string Organisation,
    string Address1,
    string Address2,
    string Address3,
    string Address4,
    string Address5,
    Guid CountryId,
    string Telephone,
    string Telephone2,
    string Fax,
    string Email,
    Guid CurrencyId,
    string Comments,
    DateTime InitialStartDate,
    string PostageArrangements,
    bool PaymentNonUK,
    string InvoiceName,
    string InvoiceOrganisation,
    string InvoiceAddress1,
    string InvoiceAddress2,
    string InvoiceAddress3,
    string InvoiceAddress4,
    string InvoiceAddress5,
    Guid InvoiceCountryId,
    string InvoiceTelephone,
    string InvoiceTelephone2,
    string InvoiceFax,
    string InvoiceEmail,
    bool IsActive,
    bool CanOrderOnline,
    DateTime? InactiveDate,
    Guid? CustomerStatusId);
