namespace PTL.Contracts.Customer;

// Same editable field set as CreateCustomerRequest. CustomerId comes from the route,
// QalNumber and InitialStartDate are preserved server-side and cannot be edited (matches
// the legacy Customer.aspx form, which never posts these back).
public sealed record UpdateCustomerRequest(
    string RegisteredFileNumber,
    string Name,
    string PreviousName,
    Guid CustomerTypeId,
    string VatNumber,
    Guid VatRatingId,
    string AccountNumber,
    string CustomerFinanceId,
    string ContactName,
    string Organisation,
    string Address1,
    string Address2,
    string Address3,
    string Address4,
    string Address5,
    Guid CountryId,
    string Telephone,
    string Telephone2,
    string Fax,
    string Email,
    Guid CurrencyId,
    string Comments,
    string PostageArrangements,
    bool PaymentNonUK,
    string InvoiceName,
    string InvoiceOrganisation,
    string InvoiceAddress1,
    string InvoiceAddress2,
    string InvoiceAddress3,
    string InvoiceAddress4,
    string InvoiceAddress5,
    Guid InvoiceCountryId,
    string InvoiceTelephone,
    string InvoiceTelephone2,
    string InvoiceFax,
    string InvoiceEmail,
    bool IsActive,
    bool CanOrderOnline,
    Guid? CustomerStatusId);
